version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: drm2view
      MYSQL_USER: root2
      MYSQL_PASSWORD: passwd
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
  php:
    build: .
    volumes:
      - ./:/var/www/
      - ./public:/var/www/html
    ports:
      - 80:80
