services:
  app: 
    image: oven/bun
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: .
        target: /app
      - node_modules:/app/node_modules
    tty: true
    command: bash -c 'bun i && bun run index.ts'
volumes:
  node_modules: