services:
  app: 
    image: oven/bun
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: .
        target: /app
    tty: true
    command: bash -c 'bun run index.ts'
      # - bash
      # - /bin/bash -c "bun i && bun run index.ts"